## The makeCacheMatrix and cacheSolve functions work in together to compute the
## inverse of an input matrix. This is achieved by first creating a special
## "matrix" object which the cacheSolve function can access by using get & set 
## functions. This allows the cacheSolve function to check if the inverse has
## been previously computed and get the value from the input object, thus saving
## computation time.

## makeCacheMatrix function creates a special object which can cache the inverse
## of a matrix by building a set of 4 functions (get, set, getinv, and setinv) 
## which are contained within a list so that they can be accessed using the
## extract operator. The get & set functions are used to retrieve and assign 
## values of the input matrix, and the getinv & setinv functions perform the 
## same task for the inverse.

makeCacheMatrix <- function(x = matrix()) {
        i <- matrix()
        i <- NULL
        set <- function(y){
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinv <- function(inv) i <<- inv
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve function computes the inverse of the "matrix" object generated by 
## makeCacheMatrix. If the inverse has already been calculated, this function 
## will retreive it from the cache.The cacheSolve function first retrieves the
## inverse value from the object created by makeCacheMatrix using the getinv() 
## function. Then it checks if the result is NULL, and if it's not then there 
## is a cached inverse in the global environment which is retrieved by the

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)) {
                message("retreiving cached inverse data")
                return (i)
        }
        mat <- x$get()
        i <- solve(mat)
        x$setinv(i)
        i
}
